### ISSUE TITLE
Nouvelle page syntaxe ?

### ISSUE THREAD

**Issue by Aziraphale42** [skyfleet-blue/skyfleet#2]
Ce bloc est assez vague, peut-être une nouvelle page pour aborder plus en profondeur les classes de caractères, les quantifieurs, les groupes, les délimiteurs ?
https://github.com/skyfleet-blue/skyfleet/blob/370c959a88e16056c5f033d734e4d62ff45d1b2d/tips/regex.md?plain=1#L107-L111

**Comment by rmdes** [comment]
d'office, tu préfère travailler ici ou via le wiki, dans les deux  cas tu peux créer des pages,

si tu fait d'ici il suffit de la faire dans le bon dossier et puis tu l'a push ici, le wiki fera le sync puis un admin doit la mettre dans le menu de navigation et elle peux déjà d'office être linké a partir de /tips/regex

Bonne journée !

si il te manque quelque chose côté wiki fais signe et je te met en admin 😉

**Comment by Aziraphale42** [comment]
Ici c'est surtout un bon outil pour regrouper les échanges autour de l'outil. Et les PR seront utiles 😉

**Comment by Aziraphale42** [comment]
Petite question, dans quel dossier puis-je créer la nouvelle page, de manière qu'elle ne soit accessible que lorsqu'on aura fait une première review ?

**Comment by rmdes** [comment]
dans /tips/ https://github.com/skyfleet-blue/skyfleet/tree/main/tips

**Comment by rmdes** [comment]
Vu que le sujet est vaste et pour donner de la place à une meilleur segmentation j'ai fait en sorte que regex soit une page parente : https://github.com/skyfleet-blue/skyfleet/tree/main/tips/regex
